### ISSUE TITLE
Backstage Jira Plugin: Proxy Path in `app-config.yaml` is Ignored

### ISSUE THREAD

**Issue by hsparmar1** [RoadieHQ/roadie-backstage-plugins#502]
The Backstage Jira Plugin has been configure according to the Roadie Documentation found here: https://roadie.io/backstage/plugins/jira/. However, the plugin is failing with the following error in the Backstage UI:

After looking through the modest logging, I found that the `apiUrl` being used is as follows: /api/proxy/**jira/api**/rest/api/latest/project/YYYY. When I cURL using this URL, using the following cURL command

> curl -vvv -X GET -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXX" https://xxx.xxx.com/jira/api/rest/api/latest/project/YYYY

I get the following:

> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>302 Found</title>
> </head><body>
> <h1>Found</h1>
> <p>The document has moved <a href="https://xxx.xxx.com/shibboleth-ds/index.html?entityID=https%3A%2F%2Fxxx.xxx.com&amp;return=https%3A%2F%2Fmaestro.dhs.gov%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A2269f2bqar5ha3yat4yjy4gzrcXXXXXRGHATAFzfdbaha5ahtw3rf1e6c8d5cb">here</a>.</p>
> </body></html>
> * Connection #0 to host xxx.xxx.com left intact

However, when I use the following cURL command, I get the correct data back:

> curl -vvv -X GET -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXX" https://xxx.xxx.com/**jira**/rest/api/latest/project/YYYY

Notice that the in the second invocation of the cURL command there is no `api` after `jira`. And it delivered the correct results.

The conclusion that I drew here was that the Proxy Path should not be '/jira/api' as it is listed in the Roadie documentation, but should simply be '/jira'. When I change the Proxy Path in the Backstage `app-config.yaml` file to '/jira', 

>   '/jira':
>     target: https://xxx.xxx.com
>     headers:
>       Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXX==
>       Accept: 'application/json'
>       Content-Type: 'application/json'
>       X-Atlassian-Token: 'nocheck'
>       User-Agent: 'Backstage'

I find that that change to the Proxy Path is not being picked up by the Jira Plugin. Looking through the code, it should be picked up and used by the application in the following line:

> https://github.com/RoadieHQ/roadie-backstage-plugins/blob/58067422cf6410948e73042903b918cbcc5148fc/plugins/frontend/backstage-plugin-jira/src/api/index.ts#L46

And the `apiUrl` should resolve the Proxy Path on the following line:

> https://github.com/RoadieHQ/roadie-backstage-plugins/blob/58067422cf6410948e73042903b918cbcc5148fc/plugins/frontend/backstage-plugin-jira/src/api/index.ts#L58

## Expected Behavior

The Jira Plugin should use the Proxy Path specified in the Backstage `app-config.yaml` file.

## Current Behavior

The Jira Plugin is defaulting to the DEFAULT_PROXY_PATH as defined in the Jira Plugin code on the following line:

> https://github.com/RoadieHQ/roadie-backstage-plugins/blob/58067422cf6410948e73042903b918cbcc5148fc/plugins/frontend/backstage-plugin-jira/src/api/index.ts#L26

## Steps to Reproduce

1. Install Roadie Jira Plugin
2. Change the Proxy Path in the Backstage `app-config.yaml` file.
3. The Proxy Path is not picked up in the Jira Plugin.

## Context

The plugin fails to work issuing either a 302 error as noted above. We are demo-ing this plugin to upper management on Friday, and advice on a fix would be much appreciated. 

And: When I click on the `Go to project -->` in the Jira card, I am taken to the following address:

> http://localhost:3000/catalog/default/component/undefined/browse/YYYY

Why is this the case?

## Your Environment

- `@backstage/plugin-catalog-react` version: ^0.6.7
- `@backstage/integration` version: ????
-  `@backstage/integration-react`:  ^0.1.15

**Comment by kissmikijr** [comment]
Thanks for opening this issue, I'll take a look at it!

**Comment by hsparmar1** [comment]
@kissmikijr, Thank you for that very nice explanation.

I am having difficult with getting the plugin to work correctly. Any advice would be much appreciated. As I mentioned, I followed the instructions completely, but am still not getting any data back from Jira for the Plugin.

Here is the relevant section of my `app-config.yaml`:

proxy:
  '/jira':
    target: https://xxx.xxx.com
    headers:
      Authorization: Basic ${BASE64_ENCODED_EMAIL:API_TOKEN} 
      Accept: 'application/json'
      Content-Type: 'application/json'
      X-Atlassian-Token: 'nocheck'
      User-Agent: 'Backstage'

The above ${BASE64_ENCODED_EMAIL:API_TOKEN} was formatted from the following string:

> harjeetp@xxx.xxx.com:XXXXXXXXXXXXXXXXXXXXXXXXXXX

> echo 'harjeetp@xxx.xxx.com:XXXXXXXXXXXXXXXXXXXXXXXXXXX' | base64

The Jira API token was defined using the Jira site: `Profile --> Personal Access Token --> Create Token`

As an aside: I too am puzzled why the following cURL command works:

> curl -vvv -X GET -H "Authorization: Bearer XXXXXXXXXXXXX" https://xxx.xxx.com/jira/rest/api/latest/project/XXXX | jq .

When I try any of the variation on the URL, I get either **302** response.

> curl -vvv -X GET -H "Authorization: Bearer XXXXXXXXXXXXX" https://xxx.xxx.com /jira/api/rest/api/latest/project/XXXX | jq .

Or a **404** response:

> curl -vvv -X GET -H "Authorization: Bearer XXXXXXXXXXXXX" https://xxx.xxx.com /rest/api/latest/project/XXXX | jq .

**Comment by kissmikijr** [comment]
I created a PR to be able to modify the proxy path but until it is merged and released (and you update to use the latest version) the plugin will expect the proxy to be `/jira/api`. 
While I was trying to reproduce your setup I realized that the bash command `base64` and the node/browser JS produces a different output as base64 and for me the JIRA API returned unauthorized when I was trying to use my base64 token that I created with the bash command `base64`.

So one thing is could you try to create the base64 string via node or the browser console? 

1.

```js
// node
new Buffer('jira-mail@example.com:hTBgqVcrcxRYpT5TCzTA9C0F').toString(
  'base64',
);
// in your browser console
btoa('jira-mail@example.com:hTBgqVcrcxRYpT5TCzTA9C0F');
```

2.

I think if for some reason your jira instance expects it to have the context in it. Could you try to configure the proxy the following way:

```yaml
proxy:
  '/jira/api':
    # Not here the addition of the /jira at the end of your URL
    target: https://xxx.xxx.com/jira
    headers:
      # Try to hardcode the token on your local setup to eliminate the possibility that something is not working with the env var substitution
      Authorization: Basic XXXXXXXXXXXXXXXXXXXX
      Accept: 'application/json'
      Content-Type: 'application/json'
      X-Atlassian-Token: 'nocheck'
      User-Agent: 'Backstage'
```

**Comment by Makkuusen** [comment]
I have the same issue as described in the beginning.

When doing this i get the expected return.
`curl -vvv -X GET -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxx" https://jira.xxxxxx.com/rest/api/latest/project/DUM` 

However this gives me a 404. 
`curl -vvv -X GET -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxx" localhost:7007/api/proxy/jira/api/rest/api/latest/project/DUM` 

Somewhere in the proxy it goes wrong, but I have no clue where.

**Comment by kissmikijr** [comment]
@Makkuusen I think in the 2. case you should be just fine to curl the proxy endpoint without the Authorization header, because your proxy should have that value and the proxy will attach this header to the request when it calls the jira API.

**Comment by brunda27anaji** [comment]
I am facing the same issue too as @Makkuusen mentioned, somewhere with the proxy path the api call is unsuccessful from the backstage: 

Using JIRA api token [auth](https://developer.atlassian.com/cloud/confluence/basic-auth-for-rest-apis/) in Curl which returned the expected data- 
```
curl -D- \
   -u myaccount@xdomain.com:XXXXXXXXXXXXXXXXXX \
   -X GET \
   -H "Content-Type: application/json" \
   https://dummy.atlassian.net/rest/api/3/project/DUM
```
However with the proxy path as in the following curl - it returned 404
```
curl -D- \
   -u myaccount@xdomain.com:XXXXXXXXXXXXXXXXXX \
   -X GET \
   -H "Content-Type: application/json" \
   localhost:7007/api/proxy/jira/api/rest/api/latest/project/DUM
```

**Comment by stephanschielke** [comment]
I ran into the same issue but it turns out I was generating the `base64` token wrongly.
Instead of
```
# -n  do not output the trailing newline
echo -n "user@example.com:api-token" | base64
```
I used
```
echo "user@example.com:api-token" | base64
```
which results in a differently encoded authorization header.

I figured this out by comparing the headers produced via `curl -v -u` and `curl -v -H`.
So please double check your token is correctly encoded.

Also FYI, there are more granular configuration options available:
```
    allowedMethods: ['GET']
    allowedHeaders:
      - 'Authorization'
```
https://backstage.io/docs/plugins/proxying#configuration

**Comment by miguelpuiggarcia** [comment]
> I created a PR to be able to modify the proxy path but until it is merged and released (and you update to use the latest version) the plugin will expect the proxy to be `/jira/api`. While I was trying to reproduce your setup I realized that the bash command `base64` and the node/browser JS produces a different output as base64 and for me the JIRA API returned unauthorized when I was trying to use my base64 token that I created with the bash command `base64`.
> 
> So one thing is could you try to create the base64 string via node or the browser console?
> 
> 
> ```js
> // node
> new Buffer('jira-mail@example.com:hTBgqVcrcxRYpT5TCzTA9C0F').toString(
>   'base64',
> );
> // in your browser console
> btoa('jira-mail@example.com:hTBgqVcrcxRYpT5TCzTA9C0F');
> ```
> 
> 
> I think if for some reason your jira instance expects it to have the context in it. Could you try to configure the proxy the following way:
> 
> ```yaml
> proxy:
>   '/jira/api':
>     # Not here the addition of the /jira at the end of your URL
>     target: https://xxx.xxx.com/jira
>     headers:
>       # Try to hardcode the token on your local setup to eliminate the possibility that something is not working with the env var substitution
>       Authorization: Basic XXXXXXXXXXXXXXXXXXXX
>       Accept: 'application/json'
>       Content-Type: 'application/json'
>       X-Atlassian-Token: 'nocheck'
>       User-Agent: 'Backstage'
> ```

Same issue. Thanks this have helper as well when getting 404

**Comment by Remyapraveen** [comment]
Hi I am trying to integrate the JIRA plugin and getting the same issue related to the URL . Getting the "failed to fetch data, status 404: Not Found" error. Is the issue resolved or is there anything that could help. TIA

**Comment by miguelpuiggarcia** [comment]
> Hi I am trying to integrate the JIRA plugin and getting the same issue related to the URL . Getting the "failed to fetch data, status 404: Not Found" error. Is the issue resolved or is there anything that could help. TIA 

I fixed mine by specifying the Kira version (3)

**Comment by miguelpuiggarcia** [comment]
> Hi @miguelpuiggarcia, You mean specifying JIRA version (3) in the proxy config mentioned below ??
> 
> jira: # Defaults to /jira/api and can be omitted if proxy is configured for that url proxyPath: /jira/api # Add it in case your JIRA instance is connected to Confluence, in order to filter those activities # confluenceActivityFilter: wiki@uuid # Defaults to latest and can be omitted if you want to use the latest version of the api `apiVersion: latest`

I meant specify it like this:

`jira:
  # Defaults to /jira/api and can be omitted if proxy is configured for that url
  proxyPath: /jira/api
  # Add it in case your JIRA instance is connected to Confluence, in order to filter those activities
  # confluenceActivityFilter: wiki@uuid
  # Defaults to latest and can be omitted if you want to use the latest version of the api
  apiVersion: 3`

**Comment by Remyapraveen** [comment]
Hi @miguelpuiggarcia, thank you for the details. I did try out changing the 'apiversion'. But I am still unable to get it connected. It still hasn't connected to my proxypath yet. 
Have you changed the CSP part ??  Does it look the same for you too, any other changes that you have made that is varying from the plugin docs, like may be in the Catalog-info file or so?? 

`img-src: 
      # "'self'" and 'data' are from the backstage default but must be set since img-src is overriden
      - "'self'"
      - 'data:'
   
      # Allow your Jira instance for @roadiehq/backstage-plugin-jira
      - '${JIRA_URL}' `
